name: super_baraem_kidergarten
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

 #localization 
  flutter_localization: ^0.1.11 
  intl: ^0.19.0

# Networking
  mime: ^1.0.0
  http_parser: ^4.0.1
  dio: ^4.0.6

#icons
  cupertino_icons: ^1.0.2
  flutter_feather_icons: ^2.0.0+1
  lucide_icons: ^0.257.0

#statemanagment
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_hooks: ^0.18.2+1
  dropdown_button2: ^2.0.0
  pinput: ^2.2.31
  injectable: ^2.3.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1

#widget  
  flutter_svg: ^2.0.10+1
  visibility_detector: ^0.4.0+2
  modal_bottom_sheet: ^3.0.0
  cached_network_image: ^3.2.3
  lottie: ^2.3.2
  flutter_staggered_animations: ^1.1.1

 #localdatabase 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  
 #thirdparty

 #others
  
  path_provider: ^2.0.11
  provider: ^6.0.0
  image_picker: ^0.8.5+3
  package_info_plus: ^8.0.2
  open_store: ^0.5.0
  url_launcher: ^6.1.11
  get_it: ^7.6.4
  permission_handler: ^11.3.1
  crypto: ^3.0.3 

  animated_size_and_fade: ^3.0.1
  device_info_plus: ^11.1.1

  geolocator: ^10.0.1
  image_cropper: ^9.0.0
  location: ^5.0.3
  share_plus: ^7.2.1

  jwt_decoder: ^2.0.1
  badges: ^3.1.2
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  flutter_local_notifications: ^17.2.2
  app_links: ^6.3.2
  rxdart: ^0.27.7
  flutter_image_compress: ^2.3.0
  infinite_scroll_pagination: ^4.0.0
  open_settings_plus: ^0.3.3
  file_picker: ^8.3.1
  flutter_inappwebview: ^6.1.5
  mobile_device_identifier: ^0.0.3
  


  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator:
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/fonts/noto/
    - assets/fonts/somar/
    - assets/fonts/somar/SomarSans-Medium-edited.otf
    - assets/fonts/somar/SomarSans-Bold-edited.otf
    - assets/animation/
    - assets/icons/
    - assets/icons/kinder/


    

  fonts:
   
    - family: Somar
      fonts:
       
      
        - asset: assets/fonts/somar/SomarSans-Bold-edited.otf
          weight: 700
        - asset: assets/fonts/somar/SomarSans-Bold-edited.otf
          weight: 600
       
        - asset: assets/fonts/somar/SomarSans-Medium-edited.otf
          weight: 500
        - asset: assets/fonts/somar/SomarSans-Medium-edited.otf
          weight: 400
        - asset: assets/fonts/somar/SomarSans-Medium-edited.otf
          weight: 300
        - asset: assets/fonts/somar/SomarSans-Medium-edited.otf
          weight: 200
        - asset: assets/fonts/somar/SomarSans-Medium-edited.otf
          weight: 100     

    - family: Noto
      fonts:
       
      
        - asset: assets/fonts/noto/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto/NotoSans-SemiBold.ttf
          weight: 600
       
        - asset: assets/fonts/noto/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto/NotoSans-Light.ttf
          weight: 300
         
       
      